name-template: 'v$RESOLVED_VERSION '
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-templates: "$MAJOR.$MINOR.$PATCH"
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's Changed
  **Full Changelog**
  $CHANGES
  ## Contributors
  $CONTRIBUTORS


