name-template: 'v$RESOLVED_VERSION -hotfix '
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-templates: "${major}.${minor}.${patch}-hotfix"
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'  
template: |
  ## What's Changed
  $CHANGES
  ## Contributors
  $CONTRIBUTORS


