name: Check for merge conflicts

on:
  pull_request:
      branches:
        - '**'
      types: [edited, opened, synchronize]

jobs:
  check-merge-conflicts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Check for merge conflicts
      run: |
        git fetch --no-tags --prune --depth=1
        if git merge-base --is-ancestor HEAD ${{ github.event.pull_request.head.sha }}; then
          exit 0
        else
          exit 1
        fi
      continue-on-error: true

    - name: Send Slack notification
      if: ${{ failure() }}
      uses: slack/webhook-action@v2
      with:
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
        text: "There is a merge conflict in pull request <${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }} ${{
          github.event.pull_request.title }}>."
        username: "GitHub Actions"
        icon_emoji: ":warning:"
