name: Check for merge conflicts

on:
  pull_request_target:
      branches:
        - '**'
      types: [edited, opened, synchronize]

jobs:
  check-merge-conflicts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for merge conflicts
      run: |
        git fetch --no-tags --prune --depth=1
        if git merge-base --is-ancestor HEAD ${{ github.event.pull_request.head.sha }}; then
          echo "No merge conflicts detected."
          exit 0
        else
          exit 1
        fi
      continue-on-error: true

